/**
 * The media plugin's pass over the host's OpenAPI document.
 *
 * The request side of these routes is already described — the DTOs carry
 * `@ApiProperty`, and the two public routes carry `@ApiOperation` — but the
 * responses are `interface`s the swagger scanner cannot see, so every one of
 * them was published as a bare `{ '200': { description: '' } }`. This pass
 * writes the real shapes on (`packages/bootstrap/server/AGENTS.md` →
 * "The response-schema gap").
 *
 * Pure: it takes the document and mutates only the paths this plugin owns.
 */

import type { OpenApiDocument } from '@orthacms/bootstrap-server';
import type { OpenApiSchema } from './media-schemas';
import { buildMediaSchemas, ref } from './media-schemas';

/** An operation object, as far as this pass needs to see one. */
interface Operation {
    responses?: Record<string, { description?: string; content?: unknown }>;
}

/** What one operation answers with. */
type ResponseKind =
    | { kind: 'schema'; name: string }
    /**
     * Bytes, not JSON. Described as a wildcard media type carrying
     * `format: binary`, rather than left blank or given an invented JSON body:
     * the response's `Content-Type` is the asset's own stored MIME type, which
     * is per-row and cannot be enumerated in a document.
     */
    | { kind: 'binary' };

/** One operation: its success shape, its description, and its failures. */
interface OperationSpec {
    response: ResponseKind;
    description: string;
    /** The operation 404s on an id that names nothing readable. */
    notFound?: boolean;
}

/** An operation returning one of the fixed schemas. */
function schema(name: string, description: string): OperationSpec {
    return { response: { kind: 'schema', name }, description };
}

/**
 * The session (admin) routes, keyed by what follows `/media`.
 *
 * `DELETE /folders/{id}` is absent on purpose: it answers `204`, and this pass
 * only ever writes onto a 2xx key the scanner already emitted.
 */
const ADMIN_ROUTES: Record<string, Record<string, OperationSpec>> = {
    '/folders': {
        get: schema(
            'MediaFolderTree',
            'Every folder in the workspace, plus the root asset count.'
        ),
        post: schema('MediaFolderRef', 'The id of the created folder.')
    },
    '/folders/{id}': {
        patch: {
            ...schema('MediaFolderRef', 'The id of the renamed folder.'),
            notFound: true
        }
    },
    '/assets': {
        get: schema('MediaAssetPage', 'One page of the folder’s assets.'),
        post: schema(
            'MediaAsset',
            'The stored asset. A raster image has had its dimensions read and its derivatives generated by the time this returns.'
        ),
        delete: schema(
            'MediaDeleteResult',
            'How many of the requested assets were removed.'
        )
    },
    '/assets/{id}': {
        patch: {
            ...schema('MediaAsset', 'The updated asset.'),
            notFound: true
        }
    },
    '/assets/{id}/duplicate': {
        post: {
            ...schema(
                'MediaAsset',
                'The new asset — a fresh row and a fresh copy of the bytes, with its own id.'
            ),
            notFound: true
        }
    },
    '/assets/{id}/raw': {
        get: {
            response: { kind: 'binary' },
            description:
                'The asset’s bytes, served with the stored MIME type. `?variant=thumb|preview` serves a derivative when one was generated, else the original. May instead answer `302` to a signed provider URL when the deployment enables direct serve.',
            notFound: true
        }
    }
};

/**
 * The token-authenticated routes, keyed by what follows `/v1/media`.
 *
 * A separate table from {@link ADMIN_ROUTES} rather than a reuse of it. The two
 * surfaces happen to answer in the same shapes today, but describing both from
 * one table is what put the admin's schemas onto the published content contract
 * for thirteen operations — see `content/server/src/lib/docs`. Two tables and a
 * pattern that refuses `/v1/` is the cheap way that cannot happen here.
 */
const PUBLIC_ROUTES: Record<string, Record<string, OperationSpec>> = {
    '/assets': {
        post: schema(
            'MediaAsset',
            'The stored asset. Its `id` is what a content type’s media field takes.'
        )
    },
    '/assets/{id}/raw': {
        get: {
            response: { kind: 'binary' },
            description:
                'The asset’s bytes, served with the stored MIME type. `?variant=thumb|preview` serves a derivative when one was generated, else the original. May instead answer `302` to a signed provider URL when the deployment enables direct serve.',
            notFound: true
        }
    }
};

/**
 * Matches `<prefix>/v1/media<rest>`, with the rest captured.
 */
const PUBLIC_ROUTE_RE = /\/v1\/media(\/.*)?$/;

/**
 * Matches `<prefix>/media<rest>` — but only where `<rest>` starts at a real
 * media resource, so it cannot claim `/insights/media/storage` (a different
 * plugin's page, mounted under a path that merely contains the word) or
 * `/content/{typeName}/{id}/media` (content's per-entry media read). The
 * leading segment is captured so the `/v1/` spelling can be rejected outright
 * rather than merely losing a race: this pattern matches it too, and letting it
 * win is precisely the bug the content pass had.
 */
const ADMIN_ROUTE_RE = /^(.*)\/media(\/(?:folders|assets)(?:\/.*)?)$/;

/**
 * Writes a success response onto whichever 2xx key the scanner already emitted
 * — Nest answers `201` for a `@Post` and `200` elsewhere — so this never
 * invents a status code the API does not return.
 */
function setSuccessResponse(
    operation: Operation,
    content: Record<string, unknown>,
    description: string
): void {
    const responses = operation.responses ?? {};
    const key = Object.keys(responses).find((code) => /^2\d\d$/.test(code));
    if (!key || key === '204') {
        return;
    }
    responses[key] = { description, content };
    operation.responses = responses;
}

/** Adds a documented failure response, leaving any existing one alone. */
function addErrorResponse(
    operation: Operation,
    code: string,
    description: string
): void {
    const responses = operation.responses ?? {};
    if (responses[code]) {
        return;
    }
    responses[code] = { description };
    operation.responses = responses;
}

/** The `content` object for one operation's success response. */
function contentFor(response: ResponseKind): Record<string, unknown> {
    if (response.kind === 'binary') {
        return { '*/*': { schema: { type: 'string', format: 'binary' } } };
    }
    const asSchema: OpenApiSchema = ref(response.name);
    return { 'application/json': { schema: asSchema } };
}

/** Resolves a document path to its route table and the rest of the path. */
function locate(
    route: string
): {
    routes: Record<string, Record<string, OperationSpec>>;
    rest: string;
} | null {
    const publicMatch = PUBLIC_ROUTE_RE.exec(route);
    if (publicMatch) {
        return { routes: PUBLIC_ROUTES, rest: publicMatch[1] ?? '' };
    }
    const adminMatch = ADMIN_ROUTE_RE.exec(route);
    // `ADMIN_ROUTE_RE` matches the `/v1/` spelling too; anything that got past
    // the public pattern and still looks versioned is not this surface's.
    if (adminMatch && !adminMatch[1].endsWith('/v1')) {
        return { routes: ADMIN_ROUTES, rest: adminMatch[2] };
    }
    return null;
}

/** Adds this plugin's schemas to `document` and describes its own operations. */
export function describeMediaApi(document: OpenApiDocument): void {
    document.components ??= {};
    document.components.schemas ??= {};
    Object.assign(document.components.schemas, buildMediaSchemas());

    for (const [route, item] of Object.entries(document.paths)) {
        const located = locate(route);
        if (!located) {
            continue;
        }
        const byMethod = located.routes[located.rest];
        if (!byMethod) {
            continue;
        }

        for (const [method, operation] of Object.entries(
            item as Record<string, Operation>
        )) {
            const spec = byMethod[method];
            if (!spec || !operation || typeof operation !== 'object') {
                continue;
            }
            setSuccessResponse(
                operation,
                contentFor(spec.response),
                spec.description
            );
            if (spec.notFound) {
                // The same 404 for "no such asset" and "an asset in another
                // workspace", deliberately, so ids stay unprobeable — and for
                // an asset whose blob has gone missing from storage, which
                // would otherwise be a 500 that confirmed the row was real.
                addErrorResponse(
                    operation,
                    '404',
                    'No such asset or folder in this workspace. An id belonging to another workspace answers the same way, so ids cannot be probed.'
                );
            }
        }
    }
}
