import {
    Controller,
    Get,
    NotFoundException,
    Param,
    Query,
    Req,
    Res,
    UseGuards
} from '@nestjs/common';
import { ThrottlerGuard } from '@nestjs/throttler';
import type { Request, Response } from 'express';
import {
    safeRedirectPath,
    SSO_REGISTRY,
    UnknownSsoProviderError,
    type SsoProviderSummary,
    type SsoRegistry
} from '@orthacms/identity-domain';
import { Inject } from '@nestjs/common';
import { CompleteSsoUseCase } from '../../application/use-cases/complete-sso.use-case';
import { StartSsoUseCase } from '../../application/use-cases/start-sso.use-case';
import { SsoLoginFailedError } from '../../domain/errors';
import type { IdentityPluginConfig } from '../../types';
import { InjectIdentityConfig } from '../../identity.tokens';
import { ssoFailureUrl, ssoSuccessUrl } from '../../sso/sso-settings';
import { CookieService } from '../services/cookie.service';
import { Public } from '../decorators/public.decorator';

/**
 * The SSO handshake — three routes, all `@Public()` because a person signing in
 * has no session yet, and all rate-limited because they are unauthenticated and
 * two of them do real work.
 *
 * - `GET /api/auth/sso` — what the sign-in page renders its buttons from.
 *   Returns `[]` when the deployment registers no providers, rather than 404ing:
 *   "this CMS offers no SSO" is an answer, and one the client can render.
 * - `GET /api/auth/sso/:provider/start` — opens an attempt, sets the attempt
 *   cookie, redirects to the provider.
 * - `GET /api/auth/sso/:provider/callback` — verifies, signs in, redirects into
 *   the admin.
 *
 * **`OriginGuard` is deliberately absent from the callback.** It is a top-level
 * GET arriving from a third party, so there is no `Origin` header to check and
 * a browser would not send one. What protects it is the pair the core minted:
 * the attempt cookie the browser must present, and the `state` the provider must
 * echo. That is the whole reason those are generated by the core rather than by
 * an adapter.
 *
 * **Failures redirect, they do not 401.** The person is mid-navigation from an
 * identity provider; a bare status code would leave them on a blank page with
 * no way back. They land on the admin's sign-in screen with `?error=sso`, and
 * the server log holds the actual reason.
 */
@Public()
@UseGuards(ThrottlerGuard)
@Controller('auth/sso')
export class SsoController {
    constructor(
        @Inject(SSO_REGISTRY) private readonly registry: SsoRegistry,
        private readonly startSso: StartSsoUseCase,
        private readonly completeSso: CompleteSsoUseCase,
        private readonly cookies: CookieService,
        @InjectIdentityConfig() private readonly config: IdentityPluginConfig
    ) {}

    /**
     * The providers on offer, in registration order.
     *
     * Carries no hint about any particular person — no "this address uses
     * Google" — because it answers before anyone has identified themselves, and
     * an endpoint that varied by email would be an account-enumeration oracle
     * wearing a helpful face.
     */
    @Get()
    list(): SsoProviderSummary[] {
        return this.registry.catalogue();
    }

    /**
     * `invite` carries the one-time token from an invitation link, for the
     * "accept your invitation with your work account" path. It is not validated
     * here: a bad one is indistinguishable from a good one until the callback
     * looks it up, and every failure there is the same generic refusal anyway.
     */
    @Get(':provider/start')
    async start(
        @Param('provider') provider: string,
        @Query('redirect') redirect: string | undefined,
        @Query('invite') invite: string | undefined,
        @Res() res: Response
    ): Promise<void> {
        let started;
        try {
            started = await this.startSso.execute(
                provider,
                // Validated here, at the edge, so every layer below can treat
                // `redirectTo` as a string that cannot leave this origin.
                safeRedirectPath(redirect),
                invite
            );
        } catch (error) {
            throw this.toHttpError(error);
        }

        this.cookies.setSsoRequest(
            res,
            started.requestToken,
            started.expiresAt
        );
        res.redirect(302, started.url);
    }

    @Get(':provider/callback')
    async callback(
        @Param('provider') provider: string,
        @Req() req: Request,
        @Res() res: Response
    ): Promise<void> {
        // Cleared on both outcomes: an attempt is one-time, so a leftover
        // handle would ride along on the next attempt and turn one failure into
        // a provider that looks broken.
        const requestToken = this.cookies.readSsoRequest(req);

        let completed;
        try {
            completed = await this.completeSso.execute({
                provider,
                requestToken,
                params: queryParams(req),
                context: {
                    userAgent: req.headers['user-agent'] ?? null,
                    ipAddress: req.ip ?? null
                }
            });
        } catch (error) {
            this.cookies.clearSsoRequest(res);
            if (error instanceof SsoLoginFailedError) {
                res.redirect(302, ssoFailureUrl(this.config));
                return;
            }
            throw this.toHttpError(error);
        }

        this.cookies.clearSsoRequest(res);
        this.cookies.setSession(res, completed.session.token);
        res.redirect(302, ssoSuccessUrl(this.config, completed.redirectTo));
    }

    /**
     * Collapses an unregistered provider to a bare 404 and passes the rest
     * through. The registry's own message names what *is* registered, which is
     * the right thing for an operator reading a log and the wrong thing to hand
     * an anonymous caller.
     */
    private toHttpError(error: unknown): Error {
        if (error instanceof UnknownSsoProviderError) {
            return new NotFoundException();
        }
        return error instanceof Error ? error : new Error(String(error));
    }
}

/**
 * The query string as flat strings.
 *
 * Express hands back `string | string[]` — a repeated `?state=a&state=b` yields
 * an array. Taking only the string values means a duplicated parameter cannot
 * smuggle a second value past a check that looked at the first: the array is
 * dropped, the parameter reads as absent, and the sign-in is refused.
 */
function queryParams(req: Request): Record<string, string> {
    const params: Record<string, string> = {};
    for (const [key, value] of Object.entries(req.query)) {
        if (typeof value === 'string') {
            params[key] = value;
        }
    }
    return params;
}
