import { defineMessages, useIntl } from 'react-intl';

const messages = defineMessages({
    none: {
        id: 'schemaBuilder.sql.none',
        defaultMessage: 'No migration: the database does not change.'
    },
    first: {
        id: 'schemaBuilder.sql.removals',
        defaultMessage: 'Migration 1 — removals'
    },
    second: {
        id: 'schemaBuilder.sql.changes',
        defaultMessage: 'Migration 2 — everything else'
    },
    only: { id: 'schemaBuilder.sql.only', defaultMessage: 'Migration' },
    from: {
        id: 'schemaBuilder.sql.from',
        defaultMessage:
            'Generated by drizzle-kit, exactly as it will be applied.'
    }
});

/** drizzle-kit's SQL, as it will be applied — removals first when there are two. */
export function SqlTab({ sql }: { sql: readonly string[] }) {
    const intl = useIntl();
    if (sql.length === 0)
        return (
            <p className="py-3 text-sm text-muted-foreground">
                {intl.formatMessage(messages.none)}
            </p>
        );
    const titles =
        sql.length === 2 ? [messages.first, messages.second] : [messages.only];
    return (
        <div className="flex flex-col gap-3 py-3">
            <p className="text-xs text-muted-foreground">
                {intl.formatMessage(messages.from)}
            </p>
            {sql.map((statements, index) => (
                <section
                    key={index}
                    aria-label={intl.formatMessage(
                        titles[index] ?? messages.only
                    )}
                    className="flex flex-col gap-1"
                >
                    <h4 className="text-sm font-medium">
                        {intl.formatMessage(titles[index] ?? messages.only)}
                    </h4>
                    <pre
                        className="max-h-80 overflow-auto rounded-lg border bg-muted/40 p-3 font-mono text-xs"
                        tabIndex={0}
                    >
                        {statements}
                    </pre>
                </section>
            ))}
        </div>
    );
}
