import { randomUUID } from 'node:crypto';
import {
    existsSync,
    mkdirSync,
    readFileSync,
    rmSync,
    writeFileSync
} from 'node:fs';
import { join } from 'node:path';
import { sql } from 'drizzle-orm';
import request from 'supertest';
import { getDatabase } from '@orthacms/database';
import {
    closeTestApp,
    createTestApp,
    type TestApp
} from '../../support/test-app';
import {
    resetDb,
    seedActiveUser,
    seedContentGrants,
    seedWorkspace
} from '../../support/seed';
import {
    buildSourceTree,
    dropSchemaBuilderLeftovers,
    markBaselineApplied,
    removeSourceTree,
    snapshotDir,
    tableExists
} from '../../support/schema-builder';

const ADMIN_EMAIL = 'schema-apply-admin@example.com';
const CONTRIBUTOR_EMAIL = 'schema-apply-contributor@example.com';
const PASSWORD = 'SecurePass123!';

interface FieldEntry {
    key: string;
    name: string;
    spec: Record<string, unknown>;
}
interface TypeDoc {
    name: string;
    fields: FieldEntry[];
    [key: string]: unknown;
}
interface Envelope {
    document: { version: 1; types: TypeDoc[] };
    fingerprint: string;
    bootId: string;
}
interface Operation {
    id: string;
    status: string;
    step: string | null;
    migrations: string[];
    files: string[];
    error?: { code: string; message: string };
}

jest.setTimeout(180_000);

/** An app editing its own project tree, tracked in its own migrations table. */
interface Project {
    root: string;
    table: string;
    app: TestApp;
}

async function project(): Promise<Project> {
    const root = await buildSourceTree();
    const table = `__drizzle_migrations_sb_${randomUUID().slice(0, 8)}`;
    const app = await createTestApp({
        schemaBuilder: {
            enabled: true,
            projectRoot: root,
            migrationsTable: table
        }
    });
    // After the app: booting it is what opens the harness's connection.
    await markBaselineApplied(root, table);
    return { root, table, app };
}

/** A new collection the harness does not register, with one text field. */
const newType = (name: string): TypeDoc => ({
    name,
    kind: 'collection',
    publishable: false,
    paranoid: false,
    i18n: false,
    groups: [],
    fields: [{ key: `${name}.body`, name: 'body', spec: { type: 'text' } }],
    origin: 'new'
});

/**
 * `POST /api/schema-builder/apply` and `GET /api/schema-builder/operations/:id`
 * (ADR-0020): the change is generated by drizzle-kit, migrated in one
 * transaction, recorded through the outbox, and only then written to
 * `src/content/` — all or nothing. Run against real project trees built from
 * the harness's types; nothing restarts here, so each scenario that writes
 * gets a tree of its own.
 */
describe('Schema builder apply (POST /api/schema-builder/apply)', () => {
    const projects: Project[] = [];
    const created = ['content_e2e_note', 'content_e2e_fail'];

    async function login(app: TestApp, email = ADMIN_EMAIL) {
        const agent = request.agent(app.server);
        await agent
            .post('/api/auth/login')
            .send({ email, password: PASSWORD })
            .expect(201);
        return agent;
    }

    async function seedUsers(app: TestApp) {
        await resetDb();
        await seedActiveUser(app.app, {
            email: ADMIN_EMAIL,
            password: PASSWORD,
            role: 'admin'
        });
        await seedActiveUser(app.app, {
            email: CONTRIBUTOR_EMAIL,
            password: PASSWORD,
            role: 'contributor'
        });
    }

    async function current(app: TestApp): Promise<Envelope> {
        return (
            await (await login(app))
                .get('/api/schema-builder/document')
                .expect(200)
        ).body as Envelope;
    }

    /** Polls the operation until it is no longer running. */
    async function settled(app: TestApp, id: string): Promise<Operation> {
        const agent = await login(app);
        for (let attempt = 0; attempt < 240; attempt += 1) {
            const { body } = await agent
                .get(`/api/schema-builder/operations/${id}`)
                .expect(200);
            if ((body as Operation).status !== 'running')
                return body as Operation;
            await new Promise((resolve) => setTimeout(resolve, 250));
        }
        throw new Error(`apply ${id} never finished`);
    }

    beforeAll(async () => {
        // A previous run that died before its cleanup must not decide this one.
        const probe = await createTestApp();
        await dropSchemaBuilderLeftovers(created, []);
        await closeTestApp(probe);
    });

    afterAll(async () => {
        // While a connection is still open: the last app to close takes it.
        await dropSchemaBuilderLeftovers(
            created,
            projects.map(({ table }) => table)
        );
        for (const { app, root } of projects) {
            await closeTestApp(app);
            removeSourceTree(root);
        }
    });

    describe('refusals — nothing is written', () => {
        let editable: Project;
        let before: Record<string, string>;

        beforeAll(async () => {
            editable = await project();
            projects.push(editable);
        });

        beforeEach(async () => {
            await seedUsers(editable.app);
            before = snapshotDir(join(editable.root, 'src'));
        });

        afterEach(() => {
            expect(snapshotDir(join(editable.root, 'src'))).toEqual(before);
        });

        const body = (
            envelope: Envelope,
            document: unknown,
            extra: Record<string, unknown> = {}
        ) => ({
            document,
            baseFingerprint: envelope.fingerprint,
            migrationName: 'e2e_change',
            confirmed: [],
            ...extra
        });

        it('403s a role without schema:manage', async () => {
            const envelope = await current(editable.app);
            const agent = await login(editable.app, CONTRIBUTOR_EMAIL);
            await agent
                .post('/api/schema-builder/apply')
                .send(body(envelope, envelope.document))
                .expect(403);
        });

        it('400s a migration name drizzle-kit would put in a file name unchecked', async () => {
            const envelope = await current(editable.app);
            const agent = await login(editable.app);
            await agent
                .post('/api/schema-builder/apply')
                .send(
                    body(envelope, envelope.document, {
                        migrationName: '../../etc'
                    })
                )
                .expect(400);
        });

        it('409s a stale draft [schema-builder:I-06]', async () => {
            const envelope = await current(editable.app);
            const agent = await login(editable.app);
            const { body: error } = await agent
                .post('/api/schema-builder/apply')
                .send(
                    body(envelope, envelope.document, {
                        baseFingerprint: 'ffffffffffffffff'
                    })
                )
                .expect(409);
            expect(error.code).toBe('schema-builder.stale');
        });

        it('409s while another apply holds the lock [schema-builder:I-05]', async () => {
            mkdirSync(join(editable.root, '.orthacms'), { recursive: true });
            writeFileSync(
                join(editable.root, '.orthacms/apply.lock'),
                JSON.stringify({ pid: process.pid })
            );
            try {
                const envelope = await current(editable.app);
                const agent = await login(editable.app);
                const { body: error } = await agent
                    .post('/api/schema-builder/apply')
                    .send(
                        body(envelope, {
                            ...envelope.document,
                            types: [
                                ...envelope.document.types,
                                newType('e2e_note')
                            ]
                        })
                    )
                    .expect(409);
                expect(error.code).toBe('schema-builder.busy');
            } finally {
                rmSync(join(editable.root, '.orthacms/apply.lock'));
            }
        });

        it('422s a destructive change that was not confirmed by its id [schema-builder:I-07]', async () => {
            const envelope = await current(editable.app);
            const agent = await login(editable.app);
            const draft = {
                ...envelope.document,
                types: envelope.document.types.map((type) =>
                    type.name === 'test_tag'
                        ? {
                              ...type,
                              fields: type.fields.filter(
                                  (field) => field.name !== 'slug'
                              )
                          }
                        : type
                )
            };
            const { body: error } = await agent
                .post('/api/schema-builder/apply')
                .send(body(envelope, draft))
                .expect(422);
            expect(error).toMatchObject({
                code: 'schema-builder.unconfirmed',
                details: { changeIds: ['field.remove:test_tag.slug'] }
            });
        });

        it('422s a blocked change, with each one and why', async () => {
            const workspace = await seedWorkspace({
                name: 'Apply WS',
                slug: 'apply-ws'
            });
            await seedContentGrants(workspace.id, ['test_tag']);
            const envelope = await current(editable.app);
            const agent = await login(editable.app);
            const draft = {
                ...envelope.document,
                types: envelope.document.types
                    .filter((type) => type.name !== 'test_tag')
                    .map((type) => ({
                        ...type,
                        fields: type.fields.filter(
                            (field) => field.spec['to'] !== 'test_tag'
                        )
                    }))
            };
            const confirmed = [
                'field.remove:test_article.tags',
                'field.remove:test_article.pinnedTag'
            ];
            const { body: error } = await agent
                .post('/api/schema-builder/apply')
                .send(body(envelope, draft, { confirmed }))
                .expect(422);
            expect(error.code).toBe('schema-builder.blocked');
            expect(error.details.changes).toEqual(
                expect.arrayContaining([
                    { id: 'type.remove:test_tag', reason: 'type-in-use' }
                ])
            );
        });

        it('403s on a server that may not edit [schema-builder:I-01]', async () => {
            const readOnly = await createTestApp();
            try {
                const agent = await login(readOnly);
                const envelope = (
                    await agent.get('/api/schema-builder/document')
                ).body as Envelope;
                const { body: error } = await agent
                    .post('/api/schema-builder/apply')
                    .send(body(envelope, envelope.document))
                    .expect(403);
                expect(error.code).toBe('schema-builder.disabled');
            } finally {
                await closeTestApp(readOnly);
            }
        });
    });

    describe('a new type', () => {
        let editable: Project;

        beforeAll(async () => {
            editable = await project();
            projects.push(editable);
            await seedUsers(editable.app);
        });

        it('is generated, migrated, recorded and written — then the lock is free', async () => {
            const envelope = await current(editable.app);
            const agent = await login(editable.app);
            const { body: accepted } = await agent
                .post('/api/schema-builder/apply')
                .send({
                    document: {
                        ...envelope.document,
                        types: [...envelope.document.types, newType('e2e_note')]
                    },
                    baseFingerprint: envelope.fingerprint,
                    migrationName: 'add_e2e_note',
                    confirmed: []
                })
                .expect(202);
            expect(accepted).toEqual({
                operationId: expect.any(String),
                bootId: envelope.bootId
            });

            const operation = await settled(editable.app, accepted.operationId);
            expect(operation).toMatchObject({
                status: 'succeeded',
                step: null
            });
            expect(operation.migrations).toEqual([
                expect.stringMatching(/^0001_add_e2e_note\.sql$/)
            ]);
            expect(operation.files).toEqual([
                'collections/e2e_note.ts',
                'index.ts'
            ]);

            // The database has the table…
            expect(await tableExists('content_e2e_note')).toBe(true);
            // …the source has the builder's file and the manifest names it…
            const file = readFileSync(
                join(editable.root, 'src/content/collections/e2e_note.ts'),
                'utf8'
            );
            expect(file.startsWith('// @orthacms-generated')).toBe(true);
            expect(
                readFileSync(
                    join(editable.root, 'src/content/index.ts'),
                    'utf8'
                )
            ).toContain("from './collections/e2e_note'");
            // …the migration is in the folder drizzle-kit's next diff starts from…
            expect(
                existsSync(
                    join(editable.root, 'migrations', operation.migrations[0])
                )
            ).toBe(true);
            // …the apply is in the outbox…
            const events = await getDatabase().execute(
                sql`SELECT kind, payload FROM outbox_events WHERE aggregate_id = ${accepted.operationId}`
            );
            expect(events.rows).toEqual([
                expect.objectContaining({
                    kind: 'schema.applied',
                    payload: expect.objectContaining({
                        changes: ['type.add:e2e_note'],
                        migrations: operation.migrations
                    })
                })
            ]);
            // …and nothing is left behind.
            expect(
                existsSync(join(editable.root, '.orthacms/apply.lock'))
            ).toBe(false);
            expect(
                existsSync(
                    join(
                        editable.root,
                        `.orthacms/apply/${accepted.operationId}`
                    )
                )
            ).toBe(false);
        });
    });

    describe('a migration that fails', () => {
        let editable: Project;

        beforeAll(async () => {
            editable = await project();
            projects.push(editable);
            await seedUsers(editable.app);
            // A table already in the way: the generated CREATE TABLE will fail.
            await getDatabase().execute(
                sql.raw('CREATE TABLE "content_e2e_fail" (id uuid PRIMARY KEY)')
            );
        });

        it('leaves the database, the migrations and the source as they were [schema-builder:I-03]', async () => {
            const migrationsBefore = snapshotDir(
                join(editable.root, 'migrations')
            );
            const sourceBefore = snapshotDir(join(editable.root, 'src'));
            const envelope = await current(editable.app);
            const agent = await login(editable.app);
            const { body: accepted } = await agent
                .post('/api/schema-builder/apply')
                .send({
                    document: {
                        ...envelope.document,
                        types: [...envelope.document.types, newType('e2e_fail')]
                    },
                    baseFingerprint: envelope.fingerprint,
                    migrationName: 'add_e2e_fail',
                    confirmed: []
                })
                .expect(202);

            const operation = await settled(editable.app, accepted.operationId);
            expect(operation).toMatchObject({
                status: 'failed',
                step: 'migrate',
                migrations: []
            });
            expect(operation.error?.message).toBeTruthy();
            expect(snapshotDir(join(editable.root, 'migrations'))).toEqual(
                migrationsBefore
            );
            expect(snapshotDir(join(editable.root, 'src'))).toEqual(
                sourceBefore
            );
            expect(
                existsSync(join(editable.root, '.orthacms/apply.lock'))
            ).toBe(false);
        });
    });

    describe('operations', () => {
        let editable: Project;

        beforeAll(async () => {
            editable = await project();
            projects.push(editable);
            await seedUsers(editable.app);
        });

        it('404s an unknown operation and 400s an id that is not a uuid', async () => {
            const agent = await login(editable.app);
            await agent
                .get(`/api/schema-builder/operations/${randomUUID()}`)
                .expect(404);
            await agent
                .get('/api/schema-builder/operations/not-a-uuid')
                .expect(400);
        });

        it('403s a role without schema:manage', async () => {
            const agent = await login(editable.app, CONTRIBUTOR_EMAIL);
            await agent
                .get(`/api/schema-builder/operations/${randomUUID()}`)
                .expect(403);
        });
    });
});
