import { Injectable } from '@nestjs/common';
import { InjectDatabase, type Database } from '@orthacms/database';
import type { DeliveryStatus } from '@orthacms/webhooks-domain';
import {
    and,
    count,
    desc,
    eq,
    inArray,
    isNotNull,
    lt,
    lte,
    or,
    sql
} from 'drizzle-orm';
import type {
    WebhookDeliveryDetailView,
    WebhookDeliveryPage,
    WebhookDeliveryView
} from '../domain/webhook-views';
import { webhookDeliveries } from './schema/webhook-deliveries';

/** A row to queue. */
export interface DeliveryToQueue {
    /**
     * Generated by the caller, not by the database.
     *
     * The envelope frozen in `payload` carries this id and so does the
     * `X-Ortha-Delivery` header, so it has to exist before the row is written
     * or the body and the header would name different deliveries.
     */
    id: string;
    endpointId: string;
    eventId: string;
    eventKind: string;
    workspaceId: string | null;
    contentType: string | null;
    payload: unknown;
    /** The delivery this one repeats, for a redelivery; null otherwise. */
    redeliveryOf?: string | null;
}

/** A claimed row, as the worker needs it. */
export interface ClaimedDelivery {
    id: string;
    endpointId: string;
    eventId: string;
    eventKind: string;
    workspaceId: string | null;
    payload: unknown;
    attempts: number;
}

/** What one attempt produced. */
export interface AttemptOutcome {
    statusCode: number | null;
    error: string | null;
    responseSnippet: string | null;
    durationMs: number;
}

/** Filters the delivery log accepts. */
export interface DeliveryListQuery {
    status?: DeliveryStatus;
    eventKind?: string;
    page: number;
    pageSize: number;
}

/** The queue and the log, over one table. */
@Injectable()
export class WebhookDeliveryRepository {
    constructor(@InjectDatabase() private readonly db: Database) {}

    /**
     * Queues one delivery per endpoint, ignoring rows that already exist.
     *
     * `ON CONFLICT DO NOTHING` against `unique(endpoint_id, event_id)` is the
     * whole idempotency story for fan-out: outbox delivery is at-least-once, so
     * this subscriber may be handed the same event twice, and the second pass
     * must be a no-op rather than a duplicate POST.
     */
    async enqueue(deliveries: DeliveryToQueue[]): Promise<number> {
        if (deliveries.length === 0) return 0;

        const rows = await this.db
            .insert(webhookDeliveries)
            .values(
                deliveries.map((delivery) => ({
                    id: delivery.id,
                    endpointId: delivery.endpointId,
                    eventId: delivery.eventId,
                    eventKind: delivery.eventKind,
                    workspaceId: delivery.workspaceId,
                    contentType: delivery.contentType,
                    payload: delivery.payload,
                    status: 'pending' as const
                }))
            )
            .onConflictDoNothing({
                // Names the partial index explicitly: without the predicate
                // Postgres cannot tell which of the table's unique indexes this
                // arbiter refers to.
                target: [
                    webhookDeliveries.endpointId,
                    webhookDeliveries.eventId
                ],
                where: sql`${webhookDeliveries.redeliveryOf} is null`
            })
            .returning({ id: webhookDeliveries.id });

        return rows.length;
    }

    /** Queues a single delivery and returns its id (used by redelivery). */
    async enqueueOne(delivery: DeliveryToQueue): Promise<string> {
        const [row] = await this.db
            .insert(webhookDeliveries)
            .values({
                id: delivery.id,
                endpointId: delivery.endpointId,
                eventId: delivery.eventId,
                eventKind: delivery.eventKind,
                workspaceId: delivery.workspaceId,
                contentType: delivery.contentType,
                payload: delivery.payload,
                redeliveryOf: delivery.redeliveryOf ?? null,
                status: 'pending'
            })
            .returning({ id: webhookDeliveries.id });
        return row.id;
    }

    /**
     * Claims up to `limit` deliveries and marks them `delivering`.
     *
     * The transaction covers **only the claim**. That is the point of the whole
     * design: the HTTP request happens after this returns, with nothing open,
     * so a slow receiver cannot hold a database transaction or a pool client.
     *
     * `FOR UPDATE SKIP LOCKED` lets several API processes claim disjoint rows
     * without blocking each other, exactly as the outbox drain does.
     *
     * Rows stuck in `delivering` past `claimTimeoutMs` are reclaimed here
     * rather than by a separate reaper: a worker that died mid-request left the
     * row with no error, no retry and no way out, and folding the recovery into
     * the claim means there is one query to get right instead of two.
     */
    async claim(
        limit: number,
        claimTimeoutMs: number
    ): Promise<ClaimedDelivery[]> {
        const now = new Date();
        const staleBefore = new Date(now.getTime() - claimTimeoutMs);

        return this.db.transaction(async (tx) => {
            const rows = await tx
                .select({
                    id: webhookDeliveries.id,
                    endpointId: webhookDeliveries.endpointId,
                    eventId: webhookDeliveries.eventId,
                    eventKind: webhookDeliveries.eventKind,
                    workspaceId: webhookDeliveries.workspaceId,
                    payload: webhookDeliveries.payload,
                    attempts: webhookDeliveries.attempts
                })
                .from(webhookDeliveries)
                .where(
                    or(
                        and(
                            inArray(webhookDeliveries.status, [
                                'pending',
                                'failed'
                            ]),
                            or(
                                sql`${webhookDeliveries.nextAttemptAt} is null`,
                                lte(webhookDeliveries.nextAttemptAt, now)
                            )
                        ),
                        and(
                            eq(webhookDeliveries.status, 'delivering'),
                            lt(webhookDeliveries.claimedAt, staleBefore)
                        )
                    )
                )
                .orderBy(webhookDeliveries.createdAt)
                .limit(limit)
                .for('update', { skipLocked: true });

            if (rows.length === 0) return [];

            await tx
                .update(webhookDeliveries)
                .set({ status: 'delivering', claimedAt: now })
                .where(
                    inArray(
                        webhookDeliveries.id,
                        rows.map((row) => row.id)
                    )
                );

            return rows;
        });
    }

    /** Records a successful attempt. */
    async markSucceeded(id: string, outcome: AttemptOutcome): Promise<void> {
        await this.db
            .update(webhookDeliveries)
            .set({
                status: 'succeeded',
                attempts: sql`${webhookDeliveries.attempts} + 1`,
                claimedAt: null,
                nextAttemptAt: null,
                lastStatusCode: outcome.statusCode,
                lastError: null,
                responseSnippet: outcome.responseSnippet,
                durationMs: outcome.durationMs,
                completedAt: new Date()
            })
            .where(eq(webhookDeliveries.id, id));
    }

    /** Records a failed attempt that will be tried again at `nextAttemptAt`. */
    async markRetrying(
        id: string,
        outcome: AttemptOutcome,
        nextAttemptAt: Date
    ): Promise<void> {
        await this.db
            .update(webhookDeliveries)
            .set({
                status: 'failed',
                attempts: sql`${webhookDeliveries.attempts} + 1`,
                claimedAt: null,
                nextAttemptAt,
                lastStatusCode: outcome.statusCode,
                lastError: outcome.error,
                responseSnippet: outcome.responseSnippet,
                durationMs: outcome.durationMs
            })
            .where(eq(webhookDeliveries.id, id));
    }

    /** Records a final failure — no further attempt will be made. */
    async markDead(id: string, outcome: AttemptOutcome): Promise<void> {
        await this.db
            .update(webhookDeliveries)
            .set({
                status: 'dead',
                attempts: sql`${webhookDeliveries.attempts} + 1`,
                claimedAt: null,
                nextAttemptAt: null,
                lastStatusCode: outcome.statusCode,
                lastError: outcome.error,
                responseSnippet: outcome.responseSnippet,
                durationMs: outcome.durationMs,
                completedAt: new Date()
            })
            .where(eq(webhookDeliveries.id, id));
    }

    /** One page of an endpoint's delivery log, newest first. */
    async list(
        endpointId: string,
        query: DeliveryListQuery
    ): Promise<WebhookDeliveryPage> {
        const filters = [eq(webhookDeliveries.endpointId, endpointId)];
        if (query.status) {
            filters.push(eq(webhookDeliveries.status, query.status));
        }
        if (query.eventKind) {
            filters.push(eq(webhookDeliveries.eventKind, query.eventKind));
        }
        const where = and(...filters);

        const [{ total }] = await this.db
            .select({ total: count() })
            .from(webhookDeliveries)
            .where(where);

        const pageCount = Math.max(1, Math.ceil(total / query.pageSize));
        // Clamp rather than return an empty page: the log shrinks under the
        // reader (retention, a redelivery finishing), and a page number that
        // was valid a second ago should show the last page, not nothing.
        const page = Math.min(Math.max(query.page, 1), pageCount);

        const rows = await this.db
            .select()
            .from(webhookDeliveries)
            .where(where)
            .orderBy(desc(webhookDeliveries.createdAt))
            .limit(query.pageSize)
            .offset((page - 1) * query.pageSize);

        return {
            items: rows.map(toView),
            total,
            page,
            pageSize: query.pageSize,
            pageCount
        };
    }

    /**
     * One delivery with its bodies — scoped to its endpoint so an id from
     * another endpoint reads as "not found" rather than leaking across.
     */
    async findDetail(
        endpointId: string,
        deliveryId: string
    ): Promise<WebhookDeliveryDetailView | null> {
        const [row] = await this.db
            .select()
            .from(webhookDeliveries)
            .where(
                and(
                    eq(webhookDeliveries.id, deliveryId),
                    eq(webhookDeliveries.endpointId, endpointId)
                )
            )
            .limit(1);

        if (!row) return null;
        return {
            ...toView(row),
            payload: row.payload,
            responseSnippet: row.responseSnippet
        };
    }

    /**
     * Deletes completed rows older than `before`.
     *
     * Only `succeeded` and `dead` are eligible: a `failed` row is still
     * scheduled, and a `delivering` row may be in flight.
     */
    async pruneCompletedBefore(before: Date): Promise<number> {
        const rows = await this.db
            .delete(webhookDeliveries)
            .where(
                and(
                    inArray(webhookDeliveries.status, ['succeeded', 'dead']),
                    isNotNull(webhookDeliveries.completedAt),
                    lt(webhookDeliveries.completedAt, before)
                )
            )
            .returning({ id: webhookDeliveries.id });
        return rows.length;
    }
}

/** Row → the API shape, minus the bodies. */
function toView(
    row: typeof webhookDeliveries.$inferSelect
): WebhookDeliveryView {
    return {
        id: row.id,
        endpointId: row.endpointId,
        eventId: row.eventId,
        eventKind: row.eventKind,
        workspaceId: row.workspaceId,
        contentType: row.contentType,
        status: row.status as DeliveryStatus,
        attempts: row.attempts,
        nextAttemptAt: row.nextAttemptAt?.toISOString() ?? null,
        statusCode: row.lastStatusCode,
        error: row.lastError,
        durationMs: row.durationMs,
        createdAt: row.createdAt.toISOString(),
        completedAt: row.completedAt?.toISOString() ?? null
    };
}
