import { getTableName } from 'drizzle-orm';
import type { PgTable } from 'drizzle-orm/pg-core';
import { is } from 'drizzle-orm';
import { PgTable as PgTableClass } from 'drizzle-orm/pg-core';
import * as barrel from './index';
import { contentTypes } from './index';

/**
 * The one thing that can go wrong in this file and be invisible until a
 * production `relation … does not exist`.
 *
 * `drizzle.config.ts` points `schema` at `./src/content/index.ts`, and
 * drizzle-kit diffs **top-level table exports only**. A generated table that is
 * registered in `contentTypes` but never re-exported is therefore absent from
 * every migration the tool emits — silently. Nothing about the app changes: it
 * boots, the type appears in the admin, and the first read or write against it
 * fails on a table that was never created. Join tables (one per many-relation)
 * are the easy ones to forget, because nothing but this file mentions them.
 *
 * The set of tables a content type generates is not a matter of opinion —
 * `collection()` / `single()` return exactly `{ table, joinTables }` — so the
 * complete expected set is derivable, and comparing it against what this module
 * actually exports turns the trap into a failing test. This is the app-level
 * half of ORT-130; the generic case (any plugin's schema barrel) is still open
 * there.
 */

/** Every table reachable from the registry: one main table plus its join tables. */
function tablesFromRegistry(): Map<string, string> {
    const found = new Map<string, string>();
    for (const type of contentTypes) {
        found.set(getTableName(type.table), `${type.name}.table`);
        for (const [field, joinTable] of Object.entries(type.joinTables)) {
            found.set(
                getTableName(joinTable),
                `${type.name}.joinTables['${field}']`
            );
        }
    }
    return found;
}

/** Every table this module exports at the top level — what drizzle-kit sees. */
function tablesFromExports(): Map<string, string> {
    const found = new Map<string, string>();
    for (const [exportName, value] of Object.entries(barrel)) {
        if (is(value, PgTableClass)) {
            found.set(getTableName(value as PgTable), exportName);
        }
    }
    return found;
}

describe('src/content/index.ts (the drizzle-kit schema entry)', () => {
    it('re-exports every table generated by a registered content type', () => {
        const registry = tablesFromRegistry();
        const exported = tablesFromExports();

        const missing = [...registry]
            .filter(([tableName]) => !exported.has(tableName))
            .map(([tableName, origin]) => `${tableName} (${origin})`);

        expect(missing).toEqual([]);
    });

    it('exports no table that no registered content type generates', () => {
        // The mirror direction, and not merely tidiness: a leftover export for a
        // type that has been removed from `contentTypes` keeps its `CREATE TABLE`
        // in the diff, so the table survives in every new database while nothing
        // in the app can reach it. The one legitimate exception is the revision
        // store, which content-server owns and is not per-type.
        const registry = tablesFromRegistry();
        const allowed = new Set([
            ...registry.keys(),
            getTableName(barrel.contentEntryRevisionsTable)
        ]);

        const orphaned = [...tablesFromExports()]
            .filter(([tableName]) => !allowed.has(tableName))
            .map(([tableName, exportName]) => `${tableName} (${exportName})`);

        expect(orphaned).toEqual([]);
    });

    it('registers each content type exactly once, under a unique name', () => {
        // Two entries for one type double every registry read; two types sharing
        // a name collide on one physical table.
        const names = contentTypes.map((type) => type.name);
        expect([...new Set(names)]).toEqual(names);
    });

    it('exports the revision store, which is per-deployment rather than per-type', () => {
        // It is the one fixed content table, so it is not reachable from
        // `contentTypes` and the first assertion above cannot see it. Left out,
        // entry history has nowhere to be written.
        expect(getTableName(barrel.contentEntryRevisionsTable)).toBe(
            'content_entry_revisions'
        );
    });
});
